### ISSUE TITLE
Incorrect Documentation

### ISSUE THREAD

**Issue by DavidRimel** [lbolla/EMpy#10] opened 2017-01-06 23:42 UTC
In FD.py the documentation for the epsfunc states the following:

"epsfunc : function
        This is a function that provides the relative permittivity (square of the refractive index)
        as a function of the x and y position. The function must be of the form:
        ``myRelativePermittivity(x,y)``
        The function can either return a single float, corresponding the an isotropic refractive index,
        or, ir may a length-5 tuple. In the tuple case, the relative permittivity is given in the form
        (epsxx, epsxy, epsyx, epsyy, epszz)."

but I found this to not be true in fact epsfunc should take a numpy.arrays x and y and output an epsilon matrix of shape ( x.length() , y.length() ).

**Comment by DanHickstein** [comment] 2017-01-09 23:01
True! The issue is addressed by PR https://github.com/lbolla/EMpy/pull/11

**Comment by lbolla** [comment] 2017-01-10 09:11
https://github.com/lbolla/EMpy/pull/11 merged.

**Closed** 2017-01-10 09:11 UTC
